package com.example.domain;

public class CharacterSets {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARACTER_SETS.CHARACTER_SET_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String characterSetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARACTER_SETS.DEFAULT_COLLATE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String defaultCollateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARACTER_SETS.DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHARACTER_SETS.MAXLEN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxlen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARACTER_SETS.CHARACTER_SET_NAME
     *
     * @return the value of CHARACTER_SETS.CHARACTER_SET_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARACTER_SETS.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for CHARACTER_SETS.CHARACTER_SET_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName == null ? null : characterSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARACTER_SETS.DEFAULT_COLLATE_NAME
     *
     * @return the value of CHARACTER_SETS.DEFAULT_COLLATE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getDefaultCollateName() {
        return defaultCollateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARACTER_SETS.DEFAULT_COLLATE_NAME
     *
     * @param defaultCollateName the value for CHARACTER_SETS.DEFAULT_COLLATE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDefaultCollateName(String defaultCollateName) {
        this.defaultCollateName = defaultCollateName == null ? null : defaultCollateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARACTER_SETS.DESCRIPTION
     *
     * @return the value of CHARACTER_SETS.DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARACTER_SETS.DESCRIPTION
     *
     * @param description the value for CHARACTER_SETS.DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHARACTER_SETS.MAXLEN
     *
     * @return the value of CHARACTER_SETS.MAXLEN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxlen() {
        return maxlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHARACTER_SETS.MAXLEN
     *
     * @param maxlen the value for CHARACTER_SETS.MAXLEN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxlen(Long maxlen) {
        this.maxlen = maxlen;
    }
}