package com.example.domain;

public class EventsStatementsHistoryLong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.END_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long endEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SOURCE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.TIMER_START
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long timerStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.TIMER_END
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long timerEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long timerWait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.LOCK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.DIGEST
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.CURRENT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String currentSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.OBJECT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.OBJECT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String objectSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.OBJECT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String objectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long objectInstanceBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.MYSQL_ERRNO
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer mysqlErrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.RETURNED_SQLSTATE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String returnedSqlstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.MESSAGE_TEXT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String messageText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.ERRORS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long errors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.WARNINGS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long warnings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.ROWS_AFFECTED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long rowsAffected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.ROWS_SENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long rowsSent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.ROWS_EXAMINED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long rowsExamined;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.CREATED_TMP_DISK_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long createdTmpDiskTables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.CREATED_TMP_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long createdTmpTables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SELECT_FULL_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long selectFullJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SELECT_FULL_RANGE_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long selectFullRangeJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SELECT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long selectRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SELECT_RANGE_CHECK
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long selectRangeCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SELECT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long selectScan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SORT_MERGE_PASSES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sortMergePasses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SORT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sortRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SORT_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sortRows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.SORT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sortScan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.NO_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long noIndexUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.NO_GOOD_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long noGoodIndexUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.NESTING_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long nestingEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events_statements_history_long.NESTING_EVENT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String nestingEventType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.THREAD_ID
     *
     * @return the value of events_statements_history_long.THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.THREAD_ID
     *
     * @param threadId the value for events_statements_history_long.THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setThreadId(Long threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.EVENT_ID
     *
     * @return the value of events_statements_history_long.EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.EVENT_ID
     *
     * @param eventId the value for events_statements_history_long.EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.END_EVENT_ID
     *
     * @return the value of events_statements_history_long.END_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getEndEventId() {
        return endEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.END_EVENT_ID
     *
     * @param endEventId the value for events_statements_history_long.END_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setEndEventId(Long endEventId) {
        this.endEventId = endEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.EVENT_NAME
     *
     * @return the value of events_statements_history_long.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.EVENT_NAME
     *
     * @param eventName the value for events_statements_history_long.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SOURCE
     *
     * @return the value of events_statements_history_long.SOURCE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SOURCE
     *
     * @param source the value for events_statements_history_long.SOURCE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.TIMER_START
     *
     * @return the value of events_statements_history_long.TIMER_START
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTimerStart() {
        return timerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.TIMER_START
     *
     * @param timerStart the value for events_statements_history_long.TIMER_START
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTimerStart(Long timerStart) {
        this.timerStart = timerStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.TIMER_END
     *
     * @return the value of events_statements_history_long.TIMER_END
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTimerEnd() {
        return timerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.TIMER_END
     *
     * @param timerEnd the value for events_statements_history_long.TIMER_END
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTimerEnd(Long timerEnd) {
        this.timerEnd = timerEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.TIMER_WAIT
     *
     * @return the value of events_statements_history_long.TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTimerWait() {
        return timerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.TIMER_WAIT
     *
     * @param timerWait the value for events_statements_history_long.TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTimerWait(Long timerWait) {
        this.timerWait = timerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.LOCK_TIME
     *
     * @return the value of events_statements_history_long.LOCK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.LOCK_TIME
     *
     * @param lockTime the value for events_statements_history_long.LOCK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setLockTime(Long lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.DIGEST
     *
     * @return the value of events_statements_history_long.DIGEST
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.DIGEST
     *
     * @param digest the value for events_statements_history_long.DIGEST
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.CURRENT_SCHEMA
     *
     * @return the value of events_statements_history_long.CURRENT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getCurrentSchema() {
        return currentSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.CURRENT_SCHEMA
     *
     * @param currentSchema the value for events_statements_history_long.CURRENT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCurrentSchema(String currentSchema) {
        this.currentSchema = currentSchema == null ? null : currentSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.OBJECT_TYPE
     *
     * @return the value of events_statements_history_long.OBJECT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.OBJECT_TYPE
     *
     * @param objectType the value for events_statements_history_long.OBJECT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.OBJECT_SCHEMA
     *
     * @return the value of events_statements_history_long.OBJECT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getObjectSchema() {
        return objectSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.OBJECT_SCHEMA
     *
     * @param objectSchema the value for events_statements_history_long.OBJECT_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectSchema(String objectSchema) {
        this.objectSchema = objectSchema == null ? null : objectSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.OBJECT_NAME
     *
     * @return the value of events_statements_history_long.OBJECT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.OBJECT_NAME
     *
     * @param objectName the value for events_statements_history_long.OBJECT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.OBJECT_INSTANCE_BEGIN
     *
     * @return the value of events_statements_history_long.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getObjectInstanceBegin() {
        return objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.OBJECT_INSTANCE_BEGIN
     *
     * @param objectInstanceBegin the value for events_statements_history_long.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectInstanceBegin(Long objectInstanceBegin) {
        this.objectInstanceBegin = objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.MYSQL_ERRNO
     *
     * @return the value of events_statements_history_long.MYSQL_ERRNO
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getMysqlErrno() {
        return mysqlErrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.MYSQL_ERRNO
     *
     * @param mysqlErrno the value for events_statements_history_long.MYSQL_ERRNO
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMysqlErrno(Integer mysqlErrno) {
        this.mysqlErrno = mysqlErrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.RETURNED_SQLSTATE
     *
     * @return the value of events_statements_history_long.RETURNED_SQLSTATE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getReturnedSqlstate() {
        return returnedSqlstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.RETURNED_SQLSTATE
     *
     * @param returnedSqlstate the value for events_statements_history_long.RETURNED_SQLSTATE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setReturnedSqlstate(String returnedSqlstate) {
        this.returnedSqlstate = returnedSqlstate == null ? null : returnedSqlstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.MESSAGE_TEXT
     *
     * @return the value of events_statements_history_long.MESSAGE_TEXT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getMessageText() {
        return messageText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.MESSAGE_TEXT
     *
     * @param messageText the value for events_statements_history_long.MESSAGE_TEXT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMessageText(String messageText) {
        this.messageText = messageText == null ? null : messageText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.ERRORS
     *
     * @return the value of events_statements_history_long.ERRORS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.ERRORS
     *
     * @param errors the value for events_statements_history_long.ERRORS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setErrors(Long errors) {
        this.errors = errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.WARNINGS
     *
     * @return the value of events_statements_history_long.WARNINGS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getWarnings() {
        return warnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.WARNINGS
     *
     * @param warnings the value for events_statements_history_long.WARNINGS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setWarnings(Long warnings) {
        this.warnings = warnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.ROWS_AFFECTED
     *
     * @return the value of events_statements_history_long.ROWS_AFFECTED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getRowsAffected() {
        return rowsAffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.ROWS_AFFECTED
     *
     * @param rowsAffected the value for events_statements_history_long.ROWS_AFFECTED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRowsAffected(Long rowsAffected) {
        this.rowsAffected = rowsAffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.ROWS_SENT
     *
     * @return the value of events_statements_history_long.ROWS_SENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getRowsSent() {
        return rowsSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.ROWS_SENT
     *
     * @param rowsSent the value for events_statements_history_long.ROWS_SENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRowsSent(Long rowsSent) {
        this.rowsSent = rowsSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.ROWS_EXAMINED
     *
     * @return the value of events_statements_history_long.ROWS_EXAMINED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getRowsExamined() {
        return rowsExamined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.ROWS_EXAMINED
     *
     * @param rowsExamined the value for events_statements_history_long.ROWS_EXAMINED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRowsExamined(Long rowsExamined) {
        this.rowsExamined = rowsExamined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.CREATED_TMP_DISK_TABLES
     *
     * @return the value of events_statements_history_long.CREATED_TMP_DISK_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCreatedTmpDiskTables() {
        return createdTmpDiskTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.CREATED_TMP_DISK_TABLES
     *
     * @param createdTmpDiskTables the value for events_statements_history_long.CREATED_TMP_DISK_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCreatedTmpDiskTables(Long createdTmpDiskTables) {
        this.createdTmpDiskTables = createdTmpDiskTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.CREATED_TMP_TABLES
     *
     * @return the value of events_statements_history_long.CREATED_TMP_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCreatedTmpTables() {
        return createdTmpTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.CREATED_TMP_TABLES
     *
     * @param createdTmpTables the value for events_statements_history_long.CREATED_TMP_TABLES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCreatedTmpTables(Long createdTmpTables) {
        this.createdTmpTables = createdTmpTables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SELECT_FULL_JOIN
     *
     * @return the value of events_statements_history_long.SELECT_FULL_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSelectFullJoin() {
        return selectFullJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SELECT_FULL_JOIN
     *
     * @param selectFullJoin the value for events_statements_history_long.SELECT_FULL_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSelectFullJoin(Long selectFullJoin) {
        this.selectFullJoin = selectFullJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SELECT_FULL_RANGE_JOIN
     *
     * @return the value of events_statements_history_long.SELECT_FULL_RANGE_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSelectFullRangeJoin() {
        return selectFullRangeJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SELECT_FULL_RANGE_JOIN
     *
     * @param selectFullRangeJoin the value for events_statements_history_long.SELECT_FULL_RANGE_JOIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSelectFullRangeJoin(Long selectFullRangeJoin) {
        this.selectFullRangeJoin = selectFullRangeJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SELECT_RANGE
     *
     * @return the value of events_statements_history_long.SELECT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSelectRange() {
        return selectRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SELECT_RANGE
     *
     * @param selectRange the value for events_statements_history_long.SELECT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSelectRange(Long selectRange) {
        this.selectRange = selectRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SELECT_RANGE_CHECK
     *
     * @return the value of events_statements_history_long.SELECT_RANGE_CHECK
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSelectRangeCheck() {
        return selectRangeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SELECT_RANGE_CHECK
     *
     * @param selectRangeCheck the value for events_statements_history_long.SELECT_RANGE_CHECK
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSelectRangeCheck(Long selectRangeCheck) {
        this.selectRangeCheck = selectRangeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SELECT_SCAN
     *
     * @return the value of events_statements_history_long.SELECT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSelectScan() {
        return selectScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SELECT_SCAN
     *
     * @param selectScan the value for events_statements_history_long.SELECT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSelectScan(Long selectScan) {
        this.selectScan = selectScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SORT_MERGE_PASSES
     *
     * @return the value of events_statements_history_long.SORT_MERGE_PASSES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSortMergePasses() {
        return sortMergePasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SORT_MERGE_PASSES
     *
     * @param sortMergePasses the value for events_statements_history_long.SORT_MERGE_PASSES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSortMergePasses(Long sortMergePasses) {
        this.sortMergePasses = sortMergePasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SORT_RANGE
     *
     * @return the value of events_statements_history_long.SORT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSortRange() {
        return sortRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SORT_RANGE
     *
     * @param sortRange the value for events_statements_history_long.SORT_RANGE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSortRange(Long sortRange) {
        this.sortRange = sortRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SORT_ROWS
     *
     * @return the value of events_statements_history_long.SORT_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSortRows() {
        return sortRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SORT_ROWS
     *
     * @param sortRows the value for events_statements_history_long.SORT_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSortRows(Long sortRows) {
        this.sortRows = sortRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.SORT_SCAN
     *
     * @return the value of events_statements_history_long.SORT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSortScan() {
        return sortScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.SORT_SCAN
     *
     * @param sortScan the value for events_statements_history_long.SORT_SCAN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSortScan(Long sortScan) {
        this.sortScan = sortScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.NO_INDEX_USED
     *
     * @return the value of events_statements_history_long.NO_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getNoIndexUsed() {
        return noIndexUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.NO_INDEX_USED
     *
     * @param noIndexUsed the value for events_statements_history_long.NO_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNoIndexUsed(Long noIndexUsed) {
        this.noIndexUsed = noIndexUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.NO_GOOD_INDEX_USED
     *
     * @return the value of events_statements_history_long.NO_GOOD_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getNoGoodIndexUsed() {
        return noGoodIndexUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.NO_GOOD_INDEX_USED
     *
     * @param noGoodIndexUsed the value for events_statements_history_long.NO_GOOD_INDEX_USED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNoGoodIndexUsed(Long noGoodIndexUsed) {
        this.noGoodIndexUsed = noGoodIndexUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.NESTING_EVENT_ID
     *
     * @return the value of events_statements_history_long.NESTING_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getNestingEventId() {
        return nestingEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.NESTING_EVENT_ID
     *
     * @param nestingEventId the value for events_statements_history_long.NESTING_EVENT_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNestingEventId(Long nestingEventId) {
        this.nestingEventId = nestingEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events_statements_history_long.NESTING_EVENT_TYPE
     *
     * @return the value of events_statements_history_long.NESTING_EVENT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getNestingEventType() {
        return nestingEventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events_statements_history_long.NESTING_EVENT_TYPE
     *
     * @param nestingEventType the value for events_statements_history_long.NESTING_EVENT_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNestingEventType(String nestingEventType) {
        this.nestingEventType = nestingEventType == null ? null : nestingEventType.trim();
    }
}