package com.example.domain;

public class FileSummaryByInstance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.FILE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long objectInstanceBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.COUNT_STAR
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long countStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumTimerWait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MIN_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long minTimerWait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.AVG_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long avgTimerWait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MAX_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxTimerWait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.COUNT_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long countRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumTimerRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MIN_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long minTimerRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.AVG_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long avgTimerRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MAX_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxTimerRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumNumberOfBytesRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.COUNT_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long countWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumTimerWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MIN_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long minTimerWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.AVG_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long avgTimerWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MAX_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxTimerWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumNumberOfBytesWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.COUNT_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long countMisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.SUM_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long sumTimerMisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MIN_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long minTimerMisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.AVG_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long avgTimerMisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_summary_by_instance.MAX_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxTimerMisc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.FILE_NAME
     *
     * @return the value of file_summary_by_instance.FILE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.FILE_NAME
     *
     * @param fileName the value for file_summary_by_instance.FILE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.EVENT_NAME
     *
     * @return the value of file_summary_by_instance.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.EVENT_NAME
     *
     * @param eventName the value for file_summary_by_instance.EVENT_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.OBJECT_INSTANCE_BEGIN
     *
     * @return the value of file_summary_by_instance.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getObjectInstanceBegin() {
        return objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.OBJECT_INSTANCE_BEGIN
     *
     * @param objectInstanceBegin the value for file_summary_by_instance.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectInstanceBegin(Long objectInstanceBegin) {
        this.objectInstanceBegin = objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.COUNT_STAR
     *
     * @return the value of file_summary_by_instance.COUNT_STAR
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCountStar() {
        return countStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.COUNT_STAR
     *
     * @param countStar the value for file_summary_by_instance.COUNT_STAR
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCountStar(Long countStar) {
        this.countStar = countStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_TIMER_WAIT
     *
     * @return the value of file_summary_by_instance.SUM_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumTimerWait() {
        return sumTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_TIMER_WAIT
     *
     * @param sumTimerWait the value for file_summary_by_instance.SUM_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumTimerWait(Long sumTimerWait) {
        this.sumTimerWait = sumTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MIN_TIMER_WAIT
     *
     * @return the value of file_summary_by_instance.MIN_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMinTimerWait() {
        return minTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MIN_TIMER_WAIT
     *
     * @param minTimerWait the value for file_summary_by_instance.MIN_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMinTimerWait(Long minTimerWait) {
        this.minTimerWait = minTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.AVG_TIMER_WAIT
     *
     * @return the value of file_summary_by_instance.AVG_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getAvgTimerWait() {
        return avgTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.AVG_TIMER_WAIT
     *
     * @param avgTimerWait the value for file_summary_by_instance.AVG_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setAvgTimerWait(Long avgTimerWait) {
        this.avgTimerWait = avgTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MAX_TIMER_WAIT
     *
     * @return the value of file_summary_by_instance.MAX_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxTimerWait() {
        return maxTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MAX_TIMER_WAIT
     *
     * @param maxTimerWait the value for file_summary_by_instance.MAX_TIMER_WAIT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxTimerWait(Long maxTimerWait) {
        this.maxTimerWait = maxTimerWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.COUNT_READ
     *
     * @return the value of file_summary_by_instance.COUNT_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCountRead() {
        return countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.COUNT_READ
     *
     * @param countRead the value for file_summary_by_instance.COUNT_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCountRead(Long countRead) {
        this.countRead = countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_TIMER_READ
     *
     * @return the value of file_summary_by_instance.SUM_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumTimerRead() {
        return sumTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_TIMER_READ
     *
     * @param sumTimerRead the value for file_summary_by_instance.SUM_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumTimerRead(Long sumTimerRead) {
        this.sumTimerRead = sumTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MIN_TIMER_READ
     *
     * @return the value of file_summary_by_instance.MIN_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMinTimerRead() {
        return minTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MIN_TIMER_READ
     *
     * @param minTimerRead the value for file_summary_by_instance.MIN_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMinTimerRead(Long minTimerRead) {
        this.minTimerRead = minTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.AVG_TIMER_READ
     *
     * @return the value of file_summary_by_instance.AVG_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getAvgTimerRead() {
        return avgTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.AVG_TIMER_READ
     *
     * @param avgTimerRead the value for file_summary_by_instance.AVG_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setAvgTimerRead(Long avgTimerRead) {
        this.avgTimerRead = avgTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MAX_TIMER_READ
     *
     * @return the value of file_summary_by_instance.MAX_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxTimerRead() {
        return maxTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MAX_TIMER_READ
     *
     * @param maxTimerRead the value for file_summary_by_instance.MAX_TIMER_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxTimerRead(Long maxTimerRead) {
        this.maxTimerRead = maxTimerRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ
     *
     * @return the value of file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumNumberOfBytesRead() {
        return sumNumberOfBytesRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ
     *
     * @param sumNumberOfBytesRead the value for file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumNumberOfBytesRead(Long sumNumberOfBytesRead) {
        this.sumNumberOfBytesRead = sumNumberOfBytesRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.COUNT_WRITE
     *
     * @return the value of file_summary_by_instance.COUNT_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCountWrite() {
        return countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.COUNT_WRITE
     *
     * @param countWrite the value for file_summary_by_instance.COUNT_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCountWrite(Long countWrite) {
        this.countWrite = countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_TIMER_WRITE
     *
     * @return the value of file_summary_by_instance.SUM_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumTimerWrite() {
        return sumTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_TIMER_WRITE
     *
     * @param sumTimerWrite the value for file_summary_by_instance.SUM_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumTimerWrite(Long sumTimerWrite) {
        this.sumTimerWrite = sumTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MIN_TIMER_WRITE
     *
     * @return the value of file_summary_by_instance.MIN_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMinTimerWrite() {
        return minTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MIN_TIMER_WRITE
     *
     * @param minTimerWrite the value for file_summary_by_instance.MIN_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMinTimerWrite(Long minTimerWrite) {
        this.minTimerWrite = minTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.AVG_TIMER_WRITE
     *
     * @return the value of file_summary_by_instance.AVG_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getAvgTimerWrite() {
        return avgTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.AVG_TIMER_WRITE
     *
     * @param avgTimerWrite the value for file_summary_by_instance.AVG_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setAvgTimerWrite(Long avgTimerWrite) {
        this.avgTimerWrite = avgTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MAX_TIMER_WRITE
     *
     * @return the value of file_summary_by_instance.MAX_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxTimerWrite() {
        return maxTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MAX_TIMER_WRITE
     *
     * @param maxTimerWrite the value for file_summary_by_instance.MAX_TIMER_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxTimerWrite(Long maxTimerWrite) {
        this.maxTimerWrite = maxTimerWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE
     *
     * @return the value of file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumNumberOfBytesWrite() {
        return sumNumberOfBytesWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE
     *
     * @param sumNumberOfBytesWrite the value for file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumNumberOfBytesWrite(Long sumNumberOfBytesWrite) {
        this.sumNumberOfBytesWrite = sumNumberOfBytesWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.COUNT_MISC
     *
     * @return the value of file_summary_by_instance.COUNT_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCountMisc() {
        return countMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.COUNT_MISC
     *
     * @param countMisc the value for file_summary_by_instance.COUNT_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCountMisc(Long countMisc) {
        this.countMisc = countMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.SUM_TIMER_MISC
     *
     * @return the value of file_summary_by_instance.SUM_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSumTimerMisc() {
        return sumTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.SUM_TIMER_MISC
     *
     * @param sumTimerMisc the value for file_summary_by_instance.SUM_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSumTimerMisc(Long sumTimerMisc) {
        this.sumTimerMisc = sumTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MIN_TIMER_MISC
     *
     * @return the value of file_summary_by_instance.MIN_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMinTimerMisc() {
        return minTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MIN_TIMER_MISC
     *
     * @param minTimerMisc the value for file_summary_by_instance.MIN_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMinTimerMisc(Long minTimerMisc) {
        this.minTimerMisc = minTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.AVG_TIMER_MISC
     *
     * @return the value of file_summary_by_instance.AVG_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getAvgTimerMisc() {
        return avgTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.AVG_TIMER_MISC
     *
     * @param avgTimerMisc the value for file_summary_by_instance.AVG_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setAvgTimerMisc(Long avgTimerMisc) {
        this.avgTimerMisc = avgTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_summary_by_instance.MAX_TIMER_MISC
     *
     * @return the value of file_summary_by_instance.MAX_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxTimerMisc() {
        return maxTimerMisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_summary_by_instance.MAX_TIMER_MISC
     *
     * @param maxTimerMisc the value for file_summary_by_instance.MAX_TIMER_MISC
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxTimerMisc(Long maxTimerMisc) {
        this.maxTimerMisc = maxTimerMisc;
    }
}