package com.example.domain;

public class HelpKeyword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_keyword.help_keyword_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer helpKeywordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_keyword.name
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_keyword.help_keyword_id
     *
     * @return the value of help_keyword.help_keyword_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getHelpKeywordId() {
        return helpKeywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_keyword.help_keyword_id
     *
     * @param helpKeywordId the value for help_keyword.help_keyword_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setHelpKeywordId(Integer helpKeywordId) {
        this.helpKeywordId = helpKeywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_keyword.name
     *
     * @return the value of help_keyword.name
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_keyword.name
     *
     * @param name the value for help_keyword.name
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}