package com.example.domain;

import java.util.Date;

public class InnodbTrx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Date trxStarted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_requested_lock_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxRequestedLockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_wait_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Date trxWaitStarted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_weight
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_mysql_thread_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxMysqlThreadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_query
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxQuery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_operation_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxOperationState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_tables_in_use
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxTablesInUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_tables_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxTablesLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_lock_structs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxLockStructs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_lock_memory_bytes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxLockMemoryBytes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_rows_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxRowsLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_rows_modified
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxRowsModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_concurrency_tickets
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxConcurrencyTickets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_isolation_level
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxIsolationLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_unique_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer trxUniqueChecks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_foreign_key_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer trxForeignKeyChecks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_last_foreign_key_error
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String trxLastForeignKeyError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_adaptive_hash_latched
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer trxAdaptiveHashLatched;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_adaptive_hash_timeout
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long trxAdaptiveHashTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_is_read_only
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer trxIsReadOnly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TRX.trx_autocommit_non_locking
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer trxAutocommitNonLocking;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_id
     *
     * @return the value of INNODB_TRX.trx_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxId() {
        return trxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_id
     *
     * @param trxId the value for INNODB_TRX.trx_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxId(String trxId) {
        this.trxId = trxId == null ? null : trxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_state
     *
     * @return the value of INNODB_TRX.trx_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxState() {
        return trxState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_state
     *
     * @param trxState the value for INNODB_TRX.trx_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxState(String trxState) {
        this.trxState = trxState == null ? null : trxState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_started
     *
     * @return the value of INNODB_TRX.trx_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Date getTrxStarted() {
        return trxStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_started
     *
     * @param trxStarted the value for INNODB_TRX.trx_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxStarted(Date trxStarted) {
        this.trxStarted = trxStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_requested_lock_id
     *
     * @return the value of INNODB_TRX.trx_requested_lock_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxRequestedLockId() {
        return trxRequestedLockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_requested_lock_id
     *
     * @param trxRequestedLockId the value for INNODB_TRX.trx_requested_lock_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxRequestedLockId(String trxRequestedLockId) {
        this.trxRequestedLockId = trxRequestedLockId == null ? null : trxRequestedLockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_wait_started
     *
     * @return the value of INNODB_TRX.trx_wait_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Date getTrxWaitStarted() {
        return trxWaitStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_wait_started
     *
     * @param trxWaitStarted the value for INNODB_TRX.trx_wait_started
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxWaitStarted(Date trxWaitStarted) {
        this.trxWaitStarted = trxWaitStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_weight
     *
     * @return the value of INNODB_TRX.trx_weight
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxWeight() {
        return trxWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_weight
     *
     * @param trxWeight the value for INNODB_TRX.trx_weight
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxWeight(Long trxWeight) {
        this.trxWeight = trxWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_mysql_thread_id
     *
     * @return the value of INNODB_TRX.trx_mysql_thread_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxMysqlThreadId() {
        return trxMysqlThreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_mysql_thread_id
     *
     * @param trxMysqlThreadId the value for INNODB_TRX.trx_mysql_thread_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxMysqlThreadId(Long trxMysqlThreadId) {
        this.trxMysqlThreadId = trxMysqlThreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_query
     *
     * @return the value of INNODB_TRX.trx_query
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxQuery() {
        return trxQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_query
     *
     * @param trxQuery the value for INNODB_TRX.trx_query
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxQuery(String trxQuery) {
        this.trxQuery = trxQuery == null ? null : trxQuery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_operation_state
     *
     * @return the value of INNODB_TRX.trx_operation_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxOperationState() {
        return trxOperationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_operation_state
     *
     * @param trxOperationState the value for INNODB_TRX.trx_operation_state
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxOperationState(String trxOperationState) {
        this.trxOperationState = trxOperationState == null ? null : trxOperationState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_tables_in_use
     *
     * @return the value of INNODB_TRX.trx_tables_in_use
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxTablesInUse() {
        return trxTablesInUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_tables_in_use
     *
     * @param trxTablesInUse the value for INNODB_TRX.trx_tables_in_use
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxTablesInUse(Long trxTablesInUse) {
        this.trxTablesInUse = trxTablesInUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_tables_locked
     *
     * @return the value of INNODB_TRX.trx_tables_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxTablesLocked() {
        return trxTablesLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_tables_locked
     *
     * @param trxTablesLocked the value for INNODB_TRX.trx_tables_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxTablesLocked(Long trxTablesLocked) {
        this.trxTablesLocked = trxTablesLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_lock_structs
     *
     * @return the value of INNODB_TRX.trx_lock_structs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxLockStructs() {
        return trxLockStructs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_lock_structs
     *
     * @param trxLockStructs the value for INNODB_TRX.trx_lock_structs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxLockStructs(Long trxLockStructs) {
        this.trxLockStructs = trxLockStructs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_lock_memory_bytes
     *
     * @return the value of INNODB_TRX.trx_lock_memory_bytes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxLockMemoryBytes() {
        return trxLockMemoryBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_lock_memory_bytes
     *
     * @param trxLockMemoryBytes the value for INNODB_TRX.trx_lock_memory_bytes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxLockMemoryBytes(Long trxLockMemoryBytes) {
        this.trxLockMemoryBytes = trxLockMemoryBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_rows_locked
     *
     * @return the value of INNODB_TRX.trx_rows_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxRowsLocked() {
        return trxRowsLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_rows_locked
     *
     * @param trxRowsLocked the value for INNODB_TRX.trx_rows_locked
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxRowsLocked(Long trxRowsLocked) {
        this.trxRowsLocked = trxRowsLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_rows_modified
     *
     * @return the value of INNODB_TRX.trx_rows_modified
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxRowsModified() {
        return trxRowsModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_rows_modified
     *
     * @param trxRowsModified the value for INNODB_TRX.trx_rows_modified
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxRowsModified(Long trxRowsModified) {
        this.trxRowsModified = trxRowsModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_concurrency_tickets
     *
     * @return the value of INNODB_TRX.trx_concurrency_tickets
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxConcurrencyTickets() {
        return trxConcurrencyTickets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_concurrency_tickets
     *
     * @param trxConcurrencyTickets the value for INNODB_TRX.trx_concurrency_tickets
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxConcurrencyTickets(Long trxConcurrencyTickets) {
        this.trxConcurrencyTickets = trxConcurrencyTickets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_isolation_level
     *
     * @return the value of INNODB_TRX.trx_isolation_level
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxIsolationLevel() {
        return trxIsolationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_isolation_level
     *
     * @param trxIsolationLevel the value for INNODB_TRX.trx_isolation_level
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxIsolationLevel(String trxIsolationLevel) {
        this.trxIsolationLevel = trxIsolationLevel == null ? null : trxIsolationLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_unique_checks
     *
     * @return the value of INNODB_TRX.trx_unique_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTrxUniqueChecks() {
        return trxUniqueChecks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_unique_checks
     *
     * @param trxUniqueChecks the value for INNODB_TRX.trx_unique_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxUniqueChecks(Integer trxUniqueChecks) {
        this.trxUniqueChecks = trxUniqueChecks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_foreign_key_checks
     *
     * @return the value of INNODB_TRX.trx_foreign_key_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTrxForeignKeyChecks() {
        return trxForeignKeyChecks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_foreign_key_checks
     *
     * @param trxForeignKeyChecks the value for INNODB_TRX.trx_foreign_key_checks
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxForeignKeyChecks(Integer trxForeignKeyChecks) {
        this.trxForeignKeyChecks = trxForeignKeyChecks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_last_foreign_key_error
     *
     * @return the value of INNODB_TRX.trx_last_foreign_key_error
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTrxLastForeignKeyError() {
        return trxLastForeignKeyError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_last_foreign_key_error
     *
     * @param trxLastForeignKeyError the value for INNODB_TRX.trx_last_foreign_key_error
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxLastForeignKeyError(String trxLastForeignKeyError) {
        this.trxLastForeignKeyError = trxLastForeignKeyError == null ? null : trxLastForeignKeyError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_adaptive_hash_latched
     *
     * @return the value of INNODB_TRX.trx_adaptive_hash_latched
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTrxAdaptiveHashLatched() {
        return trxAdaptiveHashLatched;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_adaptive_hash_latched
     *
     * @param trxAdaptiveHashLatched the value for INNODB_TRX.trx_adaptive_hash_latched
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxAdaptiveHashLatched(Integer trxAdaptiveHashLatched) {
        this.trxAdaptiveHashLatched = trxAdaptiveHashLatched;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_adaptive_hash_timeout
     *
     * @return the value of INNODB_TRX.trx_adaptive_hash_timeout
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTrxAdaptiveHashTimeout() {
        return trxAdaptiveHashTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_adaptive_hash_timeout
     *
     * @param trxAdaptiveHashTimeout the value for INNODB_TRX.trx_adaptive_hash_timeout
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxAdaptiveHashTimeout(Long trxAdaptiveHashTimeout) {
        this.trxAdaptiveHashTimeout = trxAdaptiveHashTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_is_read_only
     *
     * @return the value of INNODB_TRX.trx_is_read_only
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTrxIsReadOnly() {
        return trxIsReadOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_is_read_only
     *
     * @param trxIsReadOnly the value for INNODB_TRX.trx_is_read_only
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxIsReadOnly(Integer trxIsReadOnly) {
        this.trxIsReadOnly = trxIsReadOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TRX.trx_autocommit_non_locking
     *
     * @return the value of INNODB_TRX.trx_autocommit_non_locking
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTrxAutocommitNonLocking() {
        return trxAutocommitNonLocking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TRX.trx_autocommit_non_locking
     *
     * @param trxAutocommitNonLocking the value for INNODB_TRX.trx_autocommit_non_locking
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTrxAutocommitNonLocking(Integer trxAutocommitNonLocking) {
        this.trxAutocommitNonLocking = trxAutocommitNonLocking;
    }
}