package com.example.domain;

public class InnodbSysDatafiles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_DATAFILES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_DATAFILES.PATH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_DATAFILES.SPACE
     *
     * @return the value of INNODB_SYS_DATAFILES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_DATAFILES.SPACE
     *
     * @param space the value for INNODB_SYS_DATAFILES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSpace(Integer space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_DATAFILES.PATH
     *
     * @return the value of INNODB_SYS_DATAFILES.PATH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_DATAFILES.PATH
     *
     * @param path the value for INNODB_SYS_DATAFILES.PATH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}