package com.example.domain;

public class InnodbCmpmem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.page_size
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer pageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.buffer_pool_instance
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer bufferPoolInstance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.pages_used
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer pagesUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.pages_free
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer pagesFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.relocation_ops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long relocationOps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMPMEM.relocation_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer relocationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.page_size
     *
     * @return the value of INNODB_CMPMEM.page_size
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.page_size
     *
     * @param pageSize the value for INNODB_CMPMEM.page_size
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.buffer_pool_instance
     *
     * @return the value of INNODB_CMPMEM.buffer_pool_instance
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getBufferPoolInstance() {
        return bufferPoolInstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.buffer_pool_instance
     *
     * @param bufferPoolInstance the value for INNODB_CMPMEM.buffer_pool_instance
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setBufferPoolInstance(Integer bufferPoolInstance) {
        this.bufferPoolInstance = bufferPoolInstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.pages_used
     *
     * @return the value of INNODB_CMPMEM.pages_used
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getPagesUsed() {
        return pagesUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.pages_used
     *
     * @param pagesUsed the value for INNODB_CMPMEM.pages_used
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPagesUsed(Integer pagesUsed) {
        this.pagesUsed = pagesUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.pages_free
     *
     * @return the value of INNODB_CMPMEM.pages_free
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getPagesFree() {
        return pagesFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.pages_free
     *
     * @param pagesFree the value for INNODB_CMPMEM.pages_free
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPagesFree(Integer pagesFree) {
        this.pagesFree = pagesFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.relocation_ops
     *
     * @return the value of INNODB_CMPMEM.relocation_ops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getRelocationOps() {
        return relocationOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.relocation_ops
     *
     * @param relocationOps the value for INNODB_CMPMEM.relocation_ops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRelocationOps(Long relocationOps) {
        this.relocationOps = relocationOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMPMEM.relocation_time
     *
     * @return the value of INNODB_CMPMEM.relocation_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getRelocationTime() {
        return relocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMPMEM.relocation_time
     *
     * @param relocationTime the value for INNODB_CMPMEM.relocation_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRelocationTime(Integer relocationTime) {
        this.relocationTime = relocationTime;
    }
}