package com.example.domain;

public class InnodbSysTablespaces {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.FLAG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.FILE_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String fileFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String rowFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer pageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_SYS_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer zipPageSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.SPACE
     *
     * @return the value of INNODB_SYS_TABLESPACES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.SPACE
     *
     * @param space the value for INNODB_SYS_TABLESPACES.SPACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSpace(Integer space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.NAME
     *
     * @return the value of INNODB_SYS_TABLESPACES.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.NAME
     *
     * @param name the value for INNODB_SYS_TABLESPACES.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.FLAG
     *
     * @return the value of INNODB_SYS_TABLESPACES.FLAG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.FLAG
     *
     * @param flag the value for INNODB_SYS_TABLESPACES.FLAG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.FILE_FORMAT
     *
     * @return the value of INNODB_SYS_TABLESPACES.FILE_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getFileFormat() {
        return fileFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.FILE_FORMAT
     *
     * @param fileFormat the value for INNODB_SYS_TABLESPACES.FILE_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat == null ? null : fileFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.ROW_FORMAT
     *
     * @return the value of INNODB_SYS_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getRowFormat() {
        return rowFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.ROW_FORMAT
     *
     * @param rowFormat the value for INNODB_SYS_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setRowFormat(String rowFormat) {
        this.rowFormat = rowFormat == null ? null : rowFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.PAGE_SIZE
     *
     * @return the value of INNODB_SYS_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.PAGE_SIZE
     *
     * @param pageSize the value for INNODB_SYS_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_SYS_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @return the value of INNODB_SYS_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getZipPageSize() {
        return zipPageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_SYS_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @param zipPageSize the value for INNODB_SYS_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setZipPageSize(Integer zipPageSize) {
        this.zipPageSize = zipPageSize;
    }
}