package com.example.domain;

public class InnodbFtIndexCache {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.WORD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.FIRST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long firstDocId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.LAST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long lastDocId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.DOC_COUNT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long docCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_INDEX_CACHE.POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.WORD
     *
     * @return the value of INNODB_FT_INDEX_CACHE.WORD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.WORD
     *
     * @param word the value for INNODB_FT_INDEX_CACHE.WORD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.FIRST_DOC_ID
     *
     * @return the value of INNODB_FT_INDEX_CACHE.FIRST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getFirstDocId() {
        return firstDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.FIRST_DOC_ID
     *
     * @param firstDocId the value for INNODB_FT_INDEX_CACHE.FIRST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setFirstDocId(Long firstDocId) {
        this.firstDocId = firstDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.LAST_DOC_ID
     *
     * @return the value of INNODB_FT_INDEX_CACHE.LAST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getLastDocId() {
        return lastDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.LAST_DOC_ID
     *
     * @param lastDocId the value for INNODB_FT_INDEX_CACHE.LAST_DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setLastDocId(Long lastDocId) {
        this.lastDocId = lastDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.DOC_COUNT
     *
     * @return the value of INNODB_FT_INDEX_CACHE.DOC_COUNT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getDocCount() {
        return docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.DOC_COUNT
     *
     * @param docCount the value for INNODB_FT_INDEX_CACHE.DOC_COUNT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDocCount(Long docCount) {
        this.docCount = docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.DOC_ID
     *
     * @return the value of INNODB_FT_INDEX_CACHE.DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.DOC_ID
     *
     * @param docId the value for INNODB_FT_INDEX_CACHE.DOC_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_INDEX_CACHE.POSITION
     *
     * @return the value of INNODB_FT_INDEX_CACHE.POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_INDEX_CACHE.POSITION
     *
     * @param position the value for INNODB_FT_INDEX_CACHE.POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPosition(Long position) {
        this.position = position;
    }
}