package com.example.domain;

import java.util.Date;

public class Messages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.content
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.room_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Long roomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.user_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messages.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.id
	 * @return  the value of messages.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.id
	 * @param id  the value for messages.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.content
	 * @return  the value of messages.content
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.content
	 * @param content  the value for messages.content
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.room_id
	 * @return  the value of messages.room_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Long getRoomId() {
		return roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.room_id
	 * @param roomId  the value for messages.room_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.user_id
	 * @return  the value of messages.user_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.user_id
	 * @param userId  the value for messages.user_id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.created_at
	 * @return  the value of messages.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.created_at
	 * @param createdAt  the value for messages.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messages.updated_at
	 * @return  the value of messages.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messages.updated_at
	 * @param updatedAt  the value for messages.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}