package com.example.domain;

public class MutexInstances {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutex_instances.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutex_instances.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long objectInstanceBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutex_instances.LOCKED_BY_THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long lockedByThreadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutex_instances.NAME
     *
     * @return the value of mutex_instances.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutex_instances.NAME
     *
     * @param name the value for mutex_instances.NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutex_instances.OBJECT_INSTANCE_BEGIN
     *
     * @return the value of mutex_instances.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getObjectInstanceBegin() {
        return objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutex_instances.OBJECT_INSTANCE_BEGIN
     *
     * @param objectInstanceBegin the value for mutex_instances.OBJECT_INSTANCE_BEGIN
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setObjectInstanceBegin(Long objectInstanceBegin) {
        this.objectInstanceBegin = objectInstanceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutex_instances.LOCKED_BY_THREAD_ID
     *
     * @return the value of mutex_instances.LOCKED_BY_THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getLockedByThreadId() {
        return lockedByThreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutex_instances.LOCKED_BY_THREAD_ID
     *
     * @param lockedByThreadId the value for mutex_instances.LOCKED_BY_THREAD_ID
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setLockedByThreadId(Long lockedByThreadId) {
        this.lockedByThreadId = lockedByThreadId;
    }
}