package com.example.domain;

public class NdbBinlogIndex extends NdbBinlogIndexKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.Position
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.File
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.inserts
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer inserts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.updates
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer updates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.deletes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer deletes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.schemaops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer schemaops;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ndb_binlog_index.gci
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer gci;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.Position
     *
     * @return the value of ndb_binlog_index.Position
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.Position
     *
     * @param position the value for ndb_binlog_index.Position
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPosition(Long position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.File
     *
     * @return the value of ndb_binlog_index.File
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.File
     *
     * @param file the value for ndb_binlog_index.File
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.inserts
     *
     * @return the value of ndb_binlog_index.inserts
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getInserts() {
        return inserts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.inserts
     *
     * @param inserts the value for ndb_binlog_index.inserts
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setInserts(Integer inserts) {
        this.inserts = inserts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.updates
     *
     * @return the value of ndb_binlog_index.updates
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getUpdates() {
        return updates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.updates
     *
     * @param updates the value for ndb_binlog_index.updates
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setUpdates(Integer updates) {
        this.updates = updates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.deletes
     *
     * @return the value of ndb_binlog_index.deletes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getDeletes() {
        return deletes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.deletes
     *
     * @param deletes the value for ndb_binlog_index.deletes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDeletes(Integer deletes) {
        this.deletes = deletes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.schemaops
     *
     * @return the value of ndb_binlog_index.schemaops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getSchemaops() {
        return schemaops;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.schemaops
     *
     * @param schemaops the value for ndb_binlog_index.schemaops
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSchemaops(Integer schemaops) {
        this.schemaops = schemaops;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ndb_binlog_index.gci
     *
     * @return the value of ndb_binlog_index.gci
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getGci() {
        return gci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ndb_binlog_index.gci
     *
     * @param gci the value for ndb_binlog_index.gci
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setGci(Integer gci) {
        this.gci = gci;
    }
}