package com.example.domain;

public class PartitionsWithBLOBs extends Partitions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String partitionExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.SUBPARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String subpartitionExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String partitionDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_EXPRESSION
     *
     * @return the value of PARTITIONS.PARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPartitionExpression() {
        return partitionExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_EXPRESSION
     *
     * @param partitionExpression the value for PARTITIONS.PARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionExpression(String partitionExpression) {
        this.partitionExpression = partitionExpression == null ? null : partitionExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.SUBPARTITION_EXPRESSION
     *
     * @return the value of PARTITIONS.SUBPARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getSubpartitionExpression() {
        return subpartitionExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.SUBPARTITION_EXPRESSION
     *
     * @param subpartitionExpression the value for PARTITIONS.SUBPARTITION_EXPRESSION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSubpartitionExpression(String subpartitionExpression) {
        this.subpartitionExpression = subpartitionExpression == null ? null : subpartitionExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_DESCRIPTION
     *
     * @return the value of PARTITIONS.PARTITION_DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPartitionDescription() {
        return partitionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_DESCRIPTION
     *
     * @param partitionDescription the value for PARTITIONS.PARTITION_DESCRIPTION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionDescription(String partitionDescription) {
        this.partitionDescription = partitionDescription == null ? null : partitionDescription.trim();
    }
}