package com.example.domain;

import java.util.Date;

public class Partitions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String partitionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.SUBPARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String subpartitionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long partitionOrdinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.SUBPARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long subpartitionOrdinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String partitionMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.SUBPARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String subpartitionMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.TABLE_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long tableRows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.AVG_ROW_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long avgRowLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long dataLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.MAX_DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long maxDataLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.INDEX_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long indexLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.DATA_FREE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long dataFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.CHECK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.CHECKSUM
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long checksum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.PARTITION_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String partitionComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.NODEGROUP
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String nodegroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTITIONS.TABLESPACE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tablespaceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.TABLE_CATALOG
     *
     * @return the value of PARTITIONS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.TABLE_CATALOG
     *
     * @param tableCatalog the value for PARTITIONS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.TABLE_SCHEMA
     *
     * @return the value of PARTITIONS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.TABLE_SCHEMA
     *
     * @param tableSchema the value for PARTITIONS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema == null ? null : tableSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.TABLE_NAME
     *
     * @return the value of PARTITIONS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.TABLE_NAME
     *
     * @param tableName the value for PARTITIONS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_NAME
     *
     * @return the value of PARTITIONS.PARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPartitionName() {
        return partitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_NAME
     *
     * @param partitionName the value for PARTITIONS.PARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionName(String partitionName) {
        this.partitionName = partitionName == null ? null : partitionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.SUBPARTITION_NAME
     *
     * @return the value of PARTITIONS.SUBPARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getSubpartitionName() {
        return subpartitionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.SUBPARTITION_NAME
     *
     * @param subpartitionName the value for PARTITIONS.SUBPARTITION_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSubpartitionName(String subpartitionName) {
        this.subpartitionName = subpartitionName == null ? null : subpartitionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_ORDINAL_POSITION
     *
     * @return the value of PARTITIONS.PARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getPartitionOrdinalPosition() {
        return partitionOrdinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_ORDINAL_POSITION
     *
     * @param partitionOrdinalPosition the value for PARTITIONS.PARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionOrdinalPosition(Long partitionOrdinalPosition) {
        this.partitionOrdinalPosition = partitionOrdinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.SUBPARTITION_ORDINAL_POSITION
     *
     * @return the value of PARTITIONS.SUBPARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSubpartitionOrdinalPosition() {
        return subpartitionOrdinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.SUBPARTITION_ORDINAL_POSITION
     *
     * @param subpartitionOrdinalPosition the value for PARTITIONS.SUBPARTITION_ORDINAL_POSITION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSubpartitionOrdinalPosition(Long subpartitionOrdinalPosition) {
        this.subpartitionOrdinalPosition = subpartitionOrdinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_METHOD
     *
     * @return the value of PARTITIONS.PARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPartitionMethod() {
        return partitionMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_METHOD
     *
     * @param partitionMethod the value for PARTITIONS.PARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionMethod(String partitionMethod) {
        this.partitionMethod = partitionMethod == null ? null : partitionMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.SUBPARTITION_METHOD
     *
     * @return the value of PARTITIONS.SUBPARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getSubpartitionMethod() {
        return subpartitionMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.SUBPARTITION_METHOD
     *
     * @param subpartitionMethod the value for PARTITIONS.SUBPARTITION_METHOD
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSubpartitionMethod(String subpartitionMethod) {
        this.subpartitionMethod = subpartitionMethod == null ? null : subpartitionMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.TABLE_ROWS
     *
     * @return the value of PARTITIONS.TABLE_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTableRows() {
        return tableRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.TABLE_ROWS
     *
     * @param tableRows the value for PARTITIONS.TABLE_ROWS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableRows(Long tableRows) {
        this.tableRows = tableRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.AVG_ROW_LENGTH
     *
     * @return the value of PARTITIONS.AVG_ROW_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getAvgRowLength() {
        return avgRowLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.AVG_ROW_LENGTH
     *
     * @param avgRowLength the value for PARTITIONS.AVG_ROW_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setAvgRowLength(Long avgRowLength) {
        this.avgRowLength = avgRowLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.DATA_LENGTH
     *
     * @return the value of PARTITIONS.DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getDataLength() {
        return dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.DATA_LENGTH
     *
     * @param dataLength the value for PARTITIONS.DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDataLength(Long dataLength) {
        this.dataLength = dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.MAX_DATA_LENGTH
     *
     * @return the value of PARTITIONS.MAX_DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getMaxDataLength() {
        return maxDataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.MAX_DATA_LENGTH
     *
     * @param maxDataLength the value for PARTITIONS.MAX_DATA_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setMaxDataLength(Long maxDataLength) {
        this.maxDataLength = maxDataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.INDEX_LENGTH
     *
     * @return the value of PARTITIONS.INDEX_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getIndexLength() {
        return indexLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.INDEX_LENGTH
     *
     * @param indexLength the value for PARTITIONS.INDEX_LENGTH
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setIndexLength(Long indexLength) {
        this.indexLength = indexLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.DATA_FREE
     *
     * @return the value of PARTITIONS.DATA_FREE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getDataFree() {
        return dataFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.DATA_FREE
     *
     * @param dataFree the value for PARTITIONS.DATA_FREE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setDataFree(Long dataFree) {
        this.dataFree = dataFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.CREATE_TIME
     *
     * @return the value of PARTITIONS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.CREATE_TIME
     *
     * @param createTime the value for PARTITIONS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.UPDATE_TIME
     *
     * @return the value of PARTITIONS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.UPDATE_TIME
     *
     * @param updateTime the value for PARTITIONS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.CHECK_TIME
     *
     * @return the value of PARTITIONS.CHECK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.CHECK_TIME
     *
     * @param checkTime the value for PARTITIONS.CHECK_TIME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.CHECKSUM
     *
     * @return the value of PARTITIONS.CHECKSUM
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getChecksum() {
        return checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.CHECKSUM
     *
     * @param checksum the value for PARTITIONS.CHECKSUM
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setChecksum(Long checksum) {
        this.checksum = checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.PARTITION_COMMENT
     *
     * @return the value of PARTITIONS.PARTITION_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPartitionComment() {
        return partitionComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.PARTITION_COMMENT
     *
     * @param partitionComment the value for PARTITIONS.PARTITION_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPartitionComment(String partitionComment) {
        this.partitionComment = partitionComment == null ? null : partitionComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.NODEGROUP
     *
     * @return the value of PARTITIONS.NODEGROUP
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getNodegroup() {
        return nodegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.NODEGROUP
     *
     * @param nodegroup the value for PARTITIONS.NODEGROUP
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNodegroup(String nodegroup) {
        this.nodegroup = nodegroup == null ? null : nodegroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTITIONS.TABLESPACE_NAME
     *
     * @return the value of PARTITIONS.TABLESPACE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTablespaceName() {
        return tablespaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTITIONS.TABLESPACE_NAME
     *
     * @param tablespaceName the value for PARTITIONS.TABLESPACE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTablespaceName(String tablespaceName) {
        this.tablespaceName = tablespaceName == null ? null : tablespaceName.trim();
    }
}