package com.example.domain;

public class ProxiesPrivKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.User
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Proxied_host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String proxiedHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Proxied_user
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String proxiedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Host
     *
     * @return the value of proxies_priv.Host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Host
     *
     * @param host the value for proxies_priv.Host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.User
     *
     * @return the value of proxies_priv.User
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.User
     *
     * @param user the value for proxies_priv.User
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Proxied_host
     *
     * @return the value of proxies_priv.Proxied_host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getProxiedHost() {
        return proxiedHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Proxied_host
     *
     * @param proxiedHost the value for proxies_priv.Proxied_host
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setProxiedHost(String proxiedHost) {
        this.proxiedHost = proxiedHost == null ? null : proxiedHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Proxied_user
     *
     * @return the value of proxies_priv.Proxied_user
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getProxiedUser() {
        return proxiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Proxied_user
     *
     * @param proxiedUser the value for proxies_priv.Proxied_user
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setProxiedUser(String proxiedUser) {
        this.proxiedUser = proxiedUser == null ? null : proxiedUser.trim();
    }
}