package com.example.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SellersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public SellersExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordIsNull() {
			addCriterion("encrypted_password is null");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordIsNotNull() {
			addCriterion("encrypted_password is not null");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordEqualTo(String value) {
			addCriterion("encrypted_password =", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordNotEqualTo(String value) {
			addCriterion("encrypted_password <>", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordGreaterThan(String value) {
			addCriterion("encrypted_password >", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("encrypted_password >=", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordLessThan(String value) {
			addCriterion("encrypted_password <", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordLessThanOrEqualTo(String value) {
			addCriterion("encrypted_password <=", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordLike(String value) {
			addCriterion("encrypted_password like", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordNotLike(String value) {
			addCriterion("encrypted_password not like", value, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordIn(List<String> values) {
			addCriterion("encrypted_password in", values, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordNotIn(List<String> values) {
			addCriterion("encrypted_password not in", values, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordBetween(String value1, String value2) {
			addCriterion("encrypted_password between", value1, value2, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andEncryptedPasswordNotBetween(String value1, String value2) {
			addCriterion("encrypted_password not between", value1, value2, "encryptedPassword");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickname is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickname is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickname =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickname <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickname >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickname >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickname <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickname <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickname like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickname not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickname in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickname not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickname between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickname not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNull() {
			addCriterion("family_name is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNotNull() {
			addCriterion("family_name is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameEqualTo(String value) {
			addCriterion("family_name =", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotEqualTo(String value) {
			addCriterion("family_name <>", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThan(String value) {
			addCriterion("family_name >", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("family_name >=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThan(String value) {
			addCriterion("family_name <", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("family_name <=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLike(String value) {
			addCriterion("family_name like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotLike(String value) {
			addCriterion("family_name not like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIn(List<String> values) {
			addCriterion("family_name in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotIn(List<String> values) {
			addCriterion("family_name not in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameBetween(String value1, String value2) {
			addCriterion("family_name between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotBetween(String value1, String value2) {
			addCriterion("family_name not between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFamilyNKIsNull() {
			addCriterion("family_n_k is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNKIsNotNull() {
			addCriterion("family_n_k is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNKEqualTo(String value) {
			addCriterion("family_n_k =", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKNotEqualTo(String value) {
			addCriterion("family_n_k <>", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKGreaterThan(String value) {
			addCriterion("family_n_k >", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKGreaterThanOrEqualTo(String value) {
			addCriterion("family_n_k >=", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKLessThan(String value) {
			addCriterion("family_n_k <", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKLessThanOrEqualTo(String value) {
			addCriterion("family_n_k <=", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKLike(String value) {
			addCriterion("family_n_k like", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKNotLike(String value) {
			addCriterion("family_n_k not like", value, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKIn(List<String> values) {
			addCriterion("family_n_k in", values, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKNotIn(List<String> values) {
			addCriterion("family_n_k not in", values, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKBetween(String value1, String value2) {
			addCriterion("family_n_k between", value1, value2, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFamilyNKNotBetween(String value1, String value2) {
			addCriterion("family_n_k not between", value1, value2, "familyNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKIsNull() {
			addCriterion("first_n_k is null");
			return (Criteria) this;
		}

		public Criteria andFirstNKIsNotNull() {
			addCriterion("first_n_k is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNKEqualTo(String value) {
			addCriterion("first_n_k =", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKNotEqualTo(String value) {
			addCriterion("first_n_k <>", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKGreaterThan(String value) {
			addCriterion("first_n_k >", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKGreaterThanOrEqualTo(String value) {
			addCriterion("first_n_k >=", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKLessThan(String value) {
			addCriterion("first_n_k <", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKLessThanOrEqualTo(String value) {
			addCriterion("first_n_k <=", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKLike(String value) {
			addCriterion("first_n_k like", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKNotLike(String value) {
			addCriterion("first_n_k not like", value, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKIn(List<String> values) {
			addCriterion("first_n_k in", values, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKNotIn(List<String> values) {
			addCriterion("first_n_k not in", values, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKBetween(String value1, String value2) {
			addCriterion("first_n_k between", value1, value2, "firstNK");
			return (Criteria) this;
		}

		public Criteria andFirstNKNotBetween(String value1, String value2) {
			addCriterion("first_n_k not between", value1, value2, "firstNK");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenIsNull() {
			addCriterion("reset_password_token is null");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenIsNotNull() {
			addCriterion("reset_password_token is not null");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenEqualTo(String value) {
			addCriterion("reset_password_token =", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenNotEqualTo(String value) {
			addCriterion("reset_password_token <>", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenGreaterThan(String value) {
			addCriterion("reset_password_token >", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenGreaterThanOrEqualTo(String value) {
			addCriterion("reset_password_token >=", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenLessThan(String value) {
			addCriterion("reset_password_token <", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenLessThanOrEqualTo(String value) {
			addCriterion("reset_password_token <=", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenLike(String value) {
			addCriterion("reset_password_token like", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenNotLike(String value) {
			addCriterion("reset_password_token not like", value, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenIn(List<String> values) {
			addCriterion("reset_password_token in", values, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenNotIn(List<String> values) {
			addCriterion("reset_password_token not in", values, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenBetween(String value1, String value2) {
			addCriterion("reset_password_token between", value1, value2, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordTokenNotBetween(String value1, String value2) {
			addCriterion("reset_password_token not between", value1, value2, "resetPasswordToken");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtIsNull() {
			addCriterion("reset_password_sent_at is null");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtIsNotNull() {
			addCriterion("reset_password_sent_at is not null");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtEqualTo(Date value) {
			addCriterion("reset_password_sent_at =", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtNotEqualTo(Date value) {
			addCriterion("reset_password_sent_at <>", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtGreaterThan(Date value) {
			addCriterion("reset_password_sent_at >", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtGreaterThanOrEqualTo(Date value) {
			addCriterion("reset_password_sent_at >=", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtLessThan(Date value) {
			addCriterion("reset_password_sent_at <", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtLessThanOrEqualTo(Date value) {
			addCriterion("reset_password_sent_at <=", value, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtIn(List<Date> values) {
			addCriterion("reset_password_sent_at in", values, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtNotIn(List<Date> values) {
			addCriterion("reset_password_sent_at not in", values, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtBetween(Date value1, Date value2) {
			addCriterion("reset_password_sent_at between", value1, value2, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andResetPasswordSentAtNotBetween(Date value1, Date value2) {
			addCriterion("reset_password_sent_at not between", value1, value2, "resetPasswordSentAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtIsNull() {
			addCriterion("remember_created_at is null");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtIsNotNull() {
			addCriterion("remember_created_at is not null");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtEqualTo(Date value) {
			addCriterion("remember_created_at =", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtNotEqualTo(Date value) {
			addCriterion("remember_created_at <>", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtGreaterThan(Date value) {
			addCriterion("remember_created_at >", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("remember_created_at >=", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtLessThan(Date value) {
			addCriterion("remember_created_at <", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("remember_created_at <=", value, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtIn(List<Date> values) {
			addCriterion("remember_created_at in", values, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtNotIn(List<Date> values) {
			addCriterion("remember_created_at not in", values, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtBetween(Date value1, Date value2) {
			addCriterion("remember_created_at between", value1, value2, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andRememberCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("remember_created_at not between", value1, value2, "rememberCreatedAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sellers
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sellers
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 26 16:23:14 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}