package com.example.domain;

public class Statistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.NON_UNIQUE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long nonUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.INDEX_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String indexSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.INDEX_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.SEQ_IN_INDEX
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long seqInIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.COLUMN_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.COLLATION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String collation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.CARDINALITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long cardinality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.SUB_PART
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long subPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.PACKED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String packed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.NULLABLE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String nullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.INDEX_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String indexType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STATISTICS.INDEX_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private String indexComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.TABLE_CATALOG
     *
     * @return the value of STATISTICS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.TABLE_CATALOG
     *
     * @param tableCatalog the value for STATISTICS.TABLE_CATALOG
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.TABLE_SCHEMA
     *
     * @return the value of STATISTICS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.TABLE_SCHEMA
     *
     * @param tableSchema the value for STATISTICS.TABLE_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema == null ? null : tableSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.TABLE_NAME
     *
     * @return the value of STATISTICS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.TABLE_NAME
     *
     * @param tableName the value for STATISTICS.TABLE_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.NON_UNIQUE
     *
     * @return the value of STATISTICS.NON_UNIQUE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getNonUnique() {
        return nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.NON_UNIQUE
     *
     * @param nonUnique the value for STATISTICS.NON_UNIQUE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNonUnique(Long nonUnique) {
        this.nonUnique = nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.INDEX_SCHEMA
     *
     * @return the value of STATISTICS.INDEX_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getIndexSchema() {
        return indexSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.INDEX_SCHEMA
     *
     * @param indexSchema the value for STATISTICS.INDEX_SCHEMA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setIndexSchema(String indexSchema) {
        this.indexSchema = indexSchema == null ? null : indexSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.INDEX_NAME
     *
     * @return the value of STATISTICS.INDEX_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.INDEX_NAME
     *
     * @param indexName the value for STATISTICS.INDEX_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.SEQ_IN_INDEX
     *
     * @return the value of STATISTICS.SEQ_IN_INDEX
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSeqInIndex() {
        return seqInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.SEQ_IN_INDEX
     *
     * @param seqInIndex the value for STATISTICS.SEQ_IN_INDEX
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSeqInIndex(Long seqInIndex) {
        this.seqInIndex = seqInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.COLUMN_NAME
     *
     * @return the value of STATISTICS.COLUMN_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.COLUMN_NAME
     *
     * @param columnName the value for STATISTICS.COLUMN_NAME
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.COLLATION
     *
     * @return the value of STATISTICS.COLLATION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getCollation() {
        return collation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.COLLATION
     *
     * @param collation the value for STATISTICS.COLLATION
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCollation(String collation) {
        this.collation = collation == null ? null : collation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.CARDINALITY
     *
     * @return the value of STATISTICS.CARDINALITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getCardinality() {
        return cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.CARDINALITY
     *
     * @param cardinality the value for STATISTICS.CARDINALITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setCardinality(Long cardinality) {
        this.cardinality = cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.SUB_PART
     *
     * @return the value of STATISTICS.SUB_PART
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getSubPart() {
        return subPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.SUB_PART
     *
     * @param subPart the value for STATISTICS.SUB_PART
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setSubPart(Long subPart) {
        this.subPart = subPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.PACKED
     *
     * @return the value of STATISTICS.PACKED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getPacked() {
        return packed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.PACKED
     *
     * @param packed the value for STATISTICS.PACKED
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setPacked(String packed) {
        this.packed = packed == null ? null : packed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.NULLABLE
     *
     * @return the value of STATISTICS.NULLABLE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.NULLABLE
     *
     * @param nullable the value for STATISTICS.NULLABLE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setNullable(String nullable) {
        this.nullable = nullable == null ? null : nullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.INDEX_TYPE
     *
     * @return the value of STATISTICS.INDEX_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.INDEX_TYPE
     *
     * @param indexType the value for STATISTICS.INDEX_TYPE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setIndexType(String indexType) {
        this.indexType = indexType == null ? null : indexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.COMMENT
     *
     * @return the value of STATISTICS.COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.COMMENT
     *
     * @param comment the value for STATISTICS.COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STATISTICS.INDEX_COMMENT
     *
     * @return the value of STATISTICS.INDEX_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public String getIndexComment() {
        return indexComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STATISTICS.INDEX_COMMENT
     *
     * @param indexComment the value for STATISTICS.INDEX_COMMENT
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setIndexComment(String indexComment) {
        this.indexComment = indexComment == null ? null : indexComment.trim();
    }
}