package com.example.domain;

public class TimeZoneTransitionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition.Time_zone_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Integer timeZoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition.Transition_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    private Long transitionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition.Time_zone_id
     *
     * @return the value of time_zone_transition.Time_zone_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Integer getTimeZoneId() {
        return timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition.Time_zone_id
     *
     * @param timeZoneId the value for time_zone_transition.Time_zone_id
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTimeZoneId(Integer timeZoneId) {
        this.timeZoneId = timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition.Transition_time
     *
     * @return the value of time_zone_transition.Transition_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public Long getTransitionTime() {
        return transitionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition.Transition_time
     *
     * @param transitionTime the value for time_zone_transition.Transition_time
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    public void setTransitionTime(Long transitionTime) {
        this.transitionTime = transitionTime;
    }
}