package com.example.domain;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.encrypted_password
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String encryptedPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.nickname
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.family_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String familyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.first_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.family_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String familyNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.first_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String firstNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.birthday
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.reset_password_token
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private String resetPasswordToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.reset_password_sent_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date resetPasswordSentAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.remember_created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date rememberCreatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.encrypted_password
	 * @return  the value of users.encrypted_password
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getEncryptedPassword() {
		return encryptedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.encrypted_password
	 * @param encryptedPassword  the value for users.encrypted_password
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword == null ? null : encryptedPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.nickname
	 * @return  the value of users.nickname
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.nickname
	 * @param nickname  the value for users.nickname
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.family_name
	 * @return  the value of users.family_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getFamilyName() {
		return familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.family_name
	 * @param familyName  the value for users.family_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setFamilyName(String familyName) {
		this.familyName = familyName == null ? null : familyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.first_name
	 * @return  the value of users.first_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.first_name
	 * @param firstName  the value for users.first_name
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName == null ? null : firstName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.family_name_kana
	 * @return  the value of users.family_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getFamilyNameKana() {
		return familyNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.family_name_kana
	 * @param familyNameKana  the value for users.family_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setFamilyNameKana(String familyNameKana) {
		this.familyNameKana = familyNameKana == null ? null : familyNameKana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.first_name_kana
	 * @return  the value of users.first_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getFirstNameKana() {
		return firstNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.first_name_kana
	 * @param firstNameKana  the value for users.first_name_kana
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setFirstNameKana(String firstNameKana) {
		this.firstNameKana = firstNameKana == null ? null : firstNameKana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.birthday
	 * @return  the value of users.birthday
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.birthday
	 * @param birthday  the value for users.birthday
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.reset_password_token
	 * @return  the value of users.reset_password_token
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public String getResetPasswordToken() {
		return resetPasswordToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.reset_password_token
	 * @param resetPasswordToken  the value for users.reset_password_token
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setResetPasswordToken(String resetPasswordToken) {
		this.resetPasswordToken = resetPasswordToken == null ? null : resetPasswordToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.reset_password_sent_at
	 * @return  the value of users.reset_password_sent_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getResetPasswordSentAt() {
		return resetPasswordSentAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.reset_password_sent_at
	 * @param resetPasswordSentAt  the value for users.reset_password_sent_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setResetPasswordSentAt(Date resetPasswordSentAt) {
		this.resetPasswordSentAt = resetPasswordSentAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.remember_created_at
	 * @return  the value of users.remember_created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getRememberCreatedAt() {
		return rememberCreatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.remember_created_at
	 * @param rememberCreatedAt  the value for users.remember_created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setRememberCreatedAt(Date rememberCreatedAt) {
		this.rememberCreatedAt = rememberCreatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.created_at
	 * @return  the value of users.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.created_at
	 * @param createdAt  the value for users.created_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.updated_at
	 * @return  the value of users.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.updated_at
	 * @param updatedAt  the value for users.updated_at
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}