package com.example.mybatis.mapper;

import com.example.domain.ActiveStorageBlobs;
import com.example.domain.ActiveStorageBlobsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActiveStorageBlobsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	long countByExample(ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int deleteByExample(ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int insert(ActiveStorageBlobs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int insertSelective(ActiveStorageBlobs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	List<ActiveStorageBlobs> selectByExampleWithBLOBs(ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	List<ActiveStorageBlobs> selectByExample(ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	ActiveStorageBlobs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByExampleSelective(@Param("record") ActiveStorageBlobs record,
			@Param("example") ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByExampleWithBLOBs(@Param("record") ActiveStorageBlobs record,
			@Param("example") ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByExample(@Param("record") ActiveStorageBlobs record,
			@Param("example") ActiveStorageBlobsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByPrimaryKeySelective(ActiveStorageBlobs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByPrimaryKeyWithBLOBs(ActiveStorageBlobs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table active_storage_blobs
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByPrimaryKey(ActiveStorageBlobs record);
}