package com.example.mybatis.mapper;

import com.example.domain.AddressUsers;
import com.example.domain.AddressUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressUsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	long countByExample(AddressUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int deleteByExample(AddressUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int insert(AddressUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int insertSelective(AddressUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	List<AddressUsers> selectByExample(AddressUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	AddressUsers selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByExampleSelective(@Param("record") AddressUsers record, @Param("example") AddressUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByExample(@Param("record") AddressUsers record, @Param("example") AddressUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByPrimaryKeySelective(AddressUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address_users
	 * @mbg.generated  Mon Apr 26 16:23:14 JST 2021
	 */
	int updateByPrimaryKey(AddressUsers record);
}