package com.example.mybatis.mapper;

import com.example.domain.CollationCharacterSetApplicability;
import com.example.domain.CollationCharacterSetApplicabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollationCharacterSetApplicabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(CollationCharacterSetApplicability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(CollationCharacterSetApplicability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<CollationCharacterSetApplicability> selectByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") CollationCharacterSetApplicability record, @Param("example") CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") CollationCharacterSetApplicability record, @Param("example") CollationCharacterSetApplicabilityExample example);
}