package com.example.mybatis.mapper;

import com.example.domain.ColumnPrivileges;
import com.example.domain.ColumnPrivilegesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnPrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(ColumnPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(ColumnPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(ColumnPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(ColumnPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<ColumnPrivileges> selectByExample(ColumnPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") ColumnPrivileges record, @Param("example") ColumnPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMN_PRIVILEGES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") ColumnPrivileges record, @Param("example") ColumnPrivilegesExample example);
}