package com.example.mybatis.mapper;

import com.example.domain.ColumnsPriv;
import com.example.domain.ColumnsPrivExample;
import com.example.domain.ColumnsPrivKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnsPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(ColumnsPrivKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(ColumnsPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(ColumnsPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<ColumnsPriv> selectByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    ColumnsPriv selectByPrimaryKey(ColumnsPrivKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") ColumnsPriv record, @Param("example") ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") ColumnsPriv record, @Param("example") ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(ColumnsPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(ColumnsPriv record);
}