package com.example.mybatis.mapper;

import com.example.domain.EventsStatementsCurrent;
import com.example.domain.EventsStatementsCurrentExample;
import com.example.domain.EventsStatementsCurrentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStatementsCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(EventsStatementsCurrentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(EventsStatementsCurrentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsCurrentWithBLOBs> selectByExampleWithBLOBs(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsCurrent> selectByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") EventsStatementsCurrentWithBLOBs record, @Param("example") EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") EventsStatementsCurrentWithBLOBs record, @Param("example") EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") EventsStatementsCurrent record, @Param("example") EventsStatementsCurrentExample example);
}