package com.example.mybatis.mapper;

import com.example.domain.Events;
import com.example.domain.EventsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Events> selectByExampleWithBLOBs(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Events> selectByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") Events record, @Param("example") EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Events record, @Param("example") EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENTS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") Events record, @Param("example") EventsExample example);
}