package com.example.mybatis.mapper;

import com.example.domain.EventsWaitsCurrent;
import com.example.domain.EventsWaitsCurrentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsWaitsCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(EventsWaitsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(EventsWaitsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(EventsWaitsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(EventsWaitsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsWaitsCurrent> selectByExample(EventsWaitsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") EventsWaitsCurrent record, @Param("example") EventsWaitsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_current
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") EventsWaitsCurrent record, @Param("example") EventsWaitsCurrentExample example);
}