package com.example.mybatis.mapper;

import com.example.domain.EventsStatementsHistoryLong;
import com.example.domain.EventsStatementsHistoryLongExample;
import com.example.domain.EventsStatementsHistoryLongWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStatementsHistoryLongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(EventsStatementsHistoryLongWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(EventsStatementsHistoryLongWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsHistoryLongWithBLOBs> selectByExampleWithBLOBs(EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsHistoryLong> selectByExample(EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") EventsStatementsHistoryLongWithBLOBs record, @Param("example") EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") EventsStatementsHistoryLongWithBLOBs record, @Param("example") EventsStatementsHistoryLongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") EventsStatementsHistoryLong record, @Param("example") EventsStatementsHistoryLongExample example);
}