package com.example.mybatis.mapper;

import com.example.domain.EventsStatementsHistory;
import com.example.domain.EventsStatementsHistoryExample;
import com.example.domain.EventsStatementsHistoryWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStatementsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(EventsStatementsHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(EventsStatementsHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsHistoryWithBLOBs> selectByExampleWithBLOBs(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<EventsStatementsHistory> selectByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") EventsStatementsHistoryWithBLOBs record, @Param("example") EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") EventsStatementsHistoryWithBLOBs record, @Param("example") EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") EventsStatementsHistory record, @Param("example") EventsStatementsHistoryExample example);
}