package com.example.mybatis.mapper;

import com.example.domain.GeneralLog;
import com.example.domain.GeneralLogExample;
import com.example.domain.GeneralLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GeneralLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(GeneralLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(GeneralLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<GeneralLogWithBLOBs> selectByExampleWithBLOBs(GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<GeneralLog> selectByExample(GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") GeneralLogWithBLOBs record, @Param("example") GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") GeneralLogWithBLOBs record, @Param("example") GeneralLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") GeneralLog record, @Param("example") GeneralLogExample example);
}