package com.example.mybatis.mapper;

import com.example.domain.HelpKeyword;
import com.example.domain.HelpKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(HelpKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(HelpKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(Integer helpKeywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(HelpKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(HelpKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<HelpKeyword> selectByExample(HelpKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    HelpKeyword selectByPrimaryKey(Integer helpKeywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") HelpKeyword record, @Param("example") HelpKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") HelpKeyword record, @Param("example") HelpKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(HelpKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_keyword
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(HelpKeyword record);
}