package com.example.mybatis.mapper;

import com.example.domain.InnodbSysTablespaces;
import com.example.domain.InnodbSysTablespacesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbSysTablespacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(InnodbSysTablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(InnodbSysTablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(InnodbSysTablespaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(InnodbSysTablespaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<InnodbSysTablespaces> selectByExample(InnodbSysTablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") InnodbSysTablespaces record, @Param("example") InnodbSysTablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLESPACES
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") InnodbSysTablespaces record, @Param("example") InnodbSysTablespacesExample example);
}