package com.example.mybatis.mapper;

import com.example.domain.OptimizerTrace;
import com.example.domain.OptimizerTraceExample;
import com.example.domain.OptimizerTraceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptimizerTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(OptimizerTraceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(OptimizerTraceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<OptimizerTraceWithBLOBs> selectByExampleWithBLOBs(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<OptimizerTrace> selectByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") OptimizerTraceWithBLOBs record, @Param("example") OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") OptimizerTraceWithBLOBs record, @Param("example") OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") OptimizerTrace record, @Param("example") OptimizerTraceExample example);
}