package com.example.mybatis.mapper;

import com.example.domain.Partitions;
import com.example.domain.PartitionsExample;
import com.example.domain.PartitionsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartitionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(PartitionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(PartitionsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<PartitionsWithBLOBs> selectByExampleWithBLOBs(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Partitions> selectByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") PartitionsWithBLOBs record, @Param("example") PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") PartitionsWithBLOBs record, @Param("example") PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") Partitions record, @Param("example") PartitionsExample example);
}