package com.example.mybatis.mapper;

import com.example.domain.Proc;
import com.example.domain.ProcExample;
import com.example.domain.ProcKey;
import com.example.domain.ProcWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(ProcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(ProcWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(ProcWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<ProcWithBLOBs> selectByExampleWithBLOBs(ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Proc> selectByExample(ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    ProcWithBLOBs selectByPrimaryKey(ProcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") ProcWithBLOBs record, @Param("example") ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ProcWithBLOBs record, @Param("example") ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") Proc record, @Param("example") ProcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(ProcWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ProcWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proc
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(Proc record);
}