package com.example.mybatis.mapper;

import com.example.domain.Prototypes;
import com.example.domain.PrototypesExample;
import com.example.domain.PrototypesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrototypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(PrototypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(PrototypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<PrototypesWithBLOBs> selectByExampleWithBLOBs(PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Prototypes> selectByExample(PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    PrototypesWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") PrototypesWithBLOBs record, @Param("example") PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") PrototypesWithBLOBs record, @Param("example") PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") Prototypes record, @Param("example") PrototypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(PrototypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(PrototypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prototypes
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(Prototypes record);
}