package com.example.mybatis.mapper;

import com.example.domain.ProxiesPriv;
import com.example.domain.ProxiesPrivExample;
import com.example.domain.ProxiesPrivKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxiesPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(ProxiesPrivKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(ProxiesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(ProxiesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<ProxiesPriv> selectByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    ProxiesPriv selectByPrimaryKey(ProxiesPrivKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") ProxiesPriv record, @Param("example") ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") ProxiesPriv record, @Param("example") ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(ProxiesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(ProxiesPriv record);
}