package com.example.mybatis.mapper;

import com.example.domain.Schemata;
import com.example.domain.SchemataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<Schemata> selectByExample(SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") Schemata record, @Param("example") SchemataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") Schemata record, @Param("example") SchemataExample example);
}