package com.example.mybatis.mapper;

import com.example.domain.SessionAccountConnectAttrs;
import com.example.domain.SessionAccountConnectAttrsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionAccountConnectAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(SessionAccountConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(SessionAccountConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SessionAccountConnectAttrs> selectByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") SessionAccountConnectAttrs record, @Param("example") SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") SessionAccountConnectAttrs record, @Param("example") SessionAccountConnectAttrsExample example);
}