package com.example.mybatis.mapper;

import com.example.domain.SlaveRelayLogInfo;
import com.example.domain.SlaveRelayLogInfoExample;
import com.example.domain.SlaveRelayLogInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveRelayLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveRelayLogInfoWithBLOBs> selectByExampleWithBLOBs(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveRelayLogInfo> selectByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    SlaveRelayLogInfoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") SlaveRelayLogInfoWithBLOBs record, @Param("example") SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SlaveRelayLogInfoWithBLOBs record, @Param("example") SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") SlaveRelayLogInfo record, @Param("example") SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(SlaveRelayLogInfo record);
}