package com.example.mybatis.mapper;

import com.example.domain.SlaveMasterInfo;
import com.example.domain.SlaveMasterInfoExample;
import com.example.domain.SlaveMasterInfoKey;
import com.example.domain.SlaveMasterInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveMasterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(SlaveMasterInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(SlaveMasterInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(SlaveMasterInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveMasterInfoWithBLOBs> selectByExampleWithBLOBs(SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveMasterInfo> selectByExample(SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    SlaveMasterInfoWithBLOBs selectByPrimaryKey(SlaveMasterInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") SlaveMasterInfoWithBLOBs record, @Param("example") SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SlaveMasterInfoWithBLOBs record, @Param("example") SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") SlaveMasterInfo record, @Param("example") SlaveMasterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(SlaveMasterInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(SlaveMasterInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_master_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(SlaveMasterInfo record);
}