package com.example.mybatis.mapper;

import com.example.domain.SlaveWorkerInfo;
import com.example.domain.SlaveWorkerInfoExample;
import com.example.domain.SlaveWorkerInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveWorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveWorkerInfoWithBLOBs> selectByExampleWithBLOBs(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlaveWorkerInfo> selectByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    SlaveWorkerInfoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") SlaveWorkerInfoWithBLOBs record, @Param("example") SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SlaveWorkerInfoWithBLOBs record, @Param("example") SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") SlaveWorkerInfo record, @Param("example") SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(SlaveWorkerInfo record);
}