package com.example.mybatis.mapper;

import com.example.domain.SlowLog;
import com.example.domain.SlowLogExample;
import com.example.domain.SlowLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlowLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(SlowLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(SlowLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlowLogWithBLOBs> selectByExampleWithBLOBs(SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<SlowLog> selectByExample(SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") SlowLogWithBLOBs record, @Param("example") SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SlowLogWithBLOBs record, @Param("example") SlowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slow_log
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") SlowLog record, @Param("example") SlowLogExample example);
}