package com.example.mybatis.mapper;

import com.example.domain.TableIoWaitsSummaryByIndexUsage;
import com.example.domain.TableIoWaitsSummaryByIndexUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableIoWaitsSummaryByIndexUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TableIoWaitsSummaryByIndexUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TableIoWaitsSummaryByIndexUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TableIoWaitsSummaryByIndexUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TableIoWaitsSummaryByIndexUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TableIoWaitsSummaryByIndexUsage> selectByExample(TableIoWaitsSummaryByIndexUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TableIoWaitsSummaryByIndexUsage record, @Param("example") TableIoWaitsSummaryByIndexUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_index_usage
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TableIoWaitsSummaryByIndexUsage record, @Param("example") TableIoWaitsSummaryByIndexUsageExample example);
}