package com.example.mybatis.mapper;

import com.example.domain.TableLockWaitsSummaryByTable;
import com.example.domain.TableLockWaitsSummaryByTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableLockWaitsSummaryByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TableLockWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TableLockWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TableLockWaitsSummaryByTable> selectByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TableLockWaitsSummaryByTable record, @Param("example") TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TableLockWaitsSummaryByTable record, @Param("example") TableLockWaitsSummaryByTableExample example);
}