package com.example.mybatis.mapper;

import com.example.domain.TableIoWaitsSummaryByTable;
import com.example.domain.TableIoWaitsSummaryByTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableIoWaitsSummaryByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TableIoWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TableIoWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TableIoWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TableIoWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TableIoWaitsSummaryByTable> selectByExample(TableIoWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TableIoWaitsSummaryByTable record, @Param("example") TableIoWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_io_waits_summary_by_table
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TableIoWaitsSummaryByTable record, @Param("example") TableIoWaitsSummaryByTableExample example);
}