package com.example.mybatis.mapper;

import com.example.domain.TimeZoneLeapSecond;
import com.example.domain.TimeZoneLeapSecondExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneLeapSecondMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TimeZoneLeapSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TimeZoneLeapSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(Long transitionTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TimeZoneLeapSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TimeZoneLeapSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TimeZoneLeapSecond> selectByExample(TimeZoneLeapSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    TimeZoneLeapSecond selectByPrimaryKey(Long transitionTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TimeZoneLeapSecond record, @Param("example") TimeZoneLeapSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TimeZoneLeapSecond record, @Param("example") TimeZoneLeapSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(TimeZoneLeapSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_leap_second
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(TimeZoneLeapSecond record);
}