package com.example.mybatis.mapper;

import com.example.domain.TimeZoneTransitionType;
import com.example.domain.TimeZoneTransitionTypeExample;
import com.example.domain.TimeZoneTransitionTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneTransitionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(TimeZoneTransitionTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TimeZoneTransitionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TimeZoneTransitionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TimeZoneTransitionType> selectByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    TimeZoneTransitionType selectByPrimaryKey(TimeZoneTransitionTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TimeZoneTransitionType record, @Param("example") TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TimeZoneTransitionType record, @Param("example") TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(TimeZoneTransitionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(TimeZoneTransitionType record);
}