package com.example.mybatis.mapper;

import com.example.domain.TimeZoneTransition;
import com.example.domain.TimeZoneTransitionExample;
import com.example.domain.TimeZoneTransitionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneTransitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    long countByExample(TimeZoneTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByExample(TimeZoneTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int deleteByPrimaryKey(TimeZoneTransitionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insert(TimeZoneTransition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int insertSelective(TimeZoneTransition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    List<TimeZoneTransition> selectByExample(TimeZoneTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    TimeZoneTransition selectByPrimaryKey(TimeZoneTransitionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExampleSelective(@Param("record") TimeZoneTransition record, @Param("example") TimeZoneTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByExample(@Param("record") TimeZoneTransition record, @Param("example") TimeZoneTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKeySelective(TimeZoneTransition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition
     *
     * @mbg.generated Mon Apr 26 16:23:14 JST 2021
     */
    int updateByPrimaryKey(TimeZoneTransition record);
}